# Generated by Django 4.2.7 on 2023-12-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('countryName', models.CharField(max_length=255)),
                ('capitalName', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('inputArea', models.SlugField()),
            ],
        ),
    ]
