# Generated by Django 4.2.7 on 2023-12-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='inputArea',
            field=models.SlugField(blank=True),
        ),
    ]
